package persistence.models;

/*
  This file was generated by generate_model.py
  Any changes you will make to it will be lost if you run the
  script again.
 
  DO NOT MODIFY!
 */

import domain.Comment;
import persistence.base.MappableModel;
import persistence.base.models.ModelFactory;

public class CommentModelFactory implements ModelFactory<Comment> {

    @Override
    public String getModelName() {
        return "Comment";
    }

    @Override
    public MappableModel<Comment> build(Comment data) {
        return new CommentModel(data);
    }
}