package persistence.models;

/*
  This file was generated by generate_model.py
  Any changes you will make to it will be lost if you run the
  script again.
 
  DO NOT MODIFY!
 */

import domain.Review;
import persistence.base.MappableModel;
import persistence.base.models.ModelFactory;

public class ReviewModelFactory implements ModelFactory<Review> {

    @Override
    public String getModelName() {
        return "Review";
    }

    @Override
    public MappableModel<Review> build(Review data) {
        return new ReviewModel(data);
    }
}