package persistence.models;

/*
  This file was generated by generate_model.py
  Any changes you will make to it will be lost if you run the
  script again.
 
  DO NOT MODIFY!
 */

import domain.Right;
import persistence.base.MappableModel;
import persistence.base.models.ModelFactory;

public class RightModelFactory implements ModelFactory<Right> {

    @Override
    public String getModelName() {
        return "Right";
    }

    @Override
    public MappableModel<Right> build(Right data) {
        return new RightModel(data);
    }
}