package persistence.models;

/*
  This file was generated by generate_model.py
  Any changes you will make to it will be lost if you run the
  script again.
 
  DO NOT MODIFY!
 */

import domain.User;
import persistence.base.MappableModel;
import persistence.base.models.ModelFactory;

public class UserModelFactory implements ModelFactory<User> {

    @Override
    public String getModelName() {
        return "User";
    }

    @Override
    public MappableModel<User> build(User data) {
        return new UserModel(data);
    }
}